language: php
php:
  - 5.5
  - 5.4
before_install:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/pho --reporter spec
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=jUiZAATYplPIeW66eqYAziuDqwollrfLe
after_script: php coveralls.php
