language: php
php:
  - 5.6
  - 5.5
  - 5.4
before_install:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phake test:unit
after_script: ./vendor/bin/phake test:coveralls
env:
  - HTTP_PROXY_REQUEST_FULLURI=0
  - HTTPS_PROXY_REQUEST_FULLURI=0
