language: php
php:
  - 5.6
  - 5.5
  - '7'
before_install:
  - composer self-update
  - composer install
script:
  - composer coverage
after_script:
  - composer coveralls
  - vendor/bin/phpmetrics src
notifications:
  email: false
