[target]

# Include source files.
includes = ["src"]

# Exclude source files.
excludes = ["vendor", "spec"]


[reporter]

# TextReporter
[reporter.text]
satisfactory = 80.0
critical = 50.0

# TreeReporter
[reporter.tree]
satisfactory = 80.0
critical = 50.0

# MarkdownReporter
[reporter.markdown]
satisfactory = 80.0
critical = 50.0
outputFilePath = "tmp/report.md"

# LcovReporter
[reporter.lcov]
outputFilePath = "tmp/report.lcov"

# ProcessingTimeReporter
[reporter.processingTime]
