[target]

# Include source files.
includes = ["src"]

# Exclude source files.
excludes = ["vendor", "spec"]


[report]
reportDirectory = "./tmp"

[report.coverageBounds]
satisfactory = 70.0
critical = 35.0


[reporter]

# TextReporter
[reporter.text]
satisfactory = 80.0
critical = 50.0

# TreeReporter
[reporter.tree]
satisfactory = 80.0
critical = 50.0

# MarkdownReporter
[reporter.markdown]
satisfactory = 80.0
critical = 50.0
outputFilePath = "report.md"

# LcovReporter
[reporter.lcov]
outputFilePath = "report.lcov"

# ProcessingTimeReporter
[reporter.processingTime]
