[target]

# Include source files.
includes = ["src"]

# Exclude source files.
excludes = ["vendor", "spec"]


[reporter]

# TextReporter
[reporter.text]
highLowerBound = 70.0
lowUpperBound = 35.0

# TreeReporter
[reporter.tree]
highLowerBound = 70.0
lowUpperBound = 35.0
 
# MarkdownReporter
[reporter.markdown]
outputFilePath = "script/report.md"

# LcovReporter
[reporter.lcov]
outputFilePath = "script/report.lcov"

# ProcessingTimeReporter
[reporter.processingTime]
